### ISSUE TITLE
Tabline no showed

### ISSUE THREAD

**Issue by Aletz-Arce** [vhakulinen/gnvim#132]
Hi,
On my current setup table is not showing.
Anyone can advise for enabled this feature.
![imagen](https://user-images.githubusercontent.com/5661038/85637092-dcb4ef80-b647-11ea-81b0-75fa4ed2a86c.png)

Thanks

**Comment by smolck** [comment]
You should be able to run gnvim with this command to show it:

`$ gnvim --disable-ext-tabline`

#61 should make this possible via init.vim/.vimrc instead of command line args, but it isn't merged yet. If you'd rather use that branch so you don't have to specify command line args, I should be able to update it for you (I think it's fairly out of date), just let me know.

**Comment by Aletz-Arce** [comment]
> You should be able to run gnvim with this command to show it:
> 
> `$ gnvim --disable-ext-tabline`
> 
> #61 should make this possible via init.vim/.vimrc instead of command line args, but it isn't merged yet. If you'd rather use that branch so you don't have to specify command line args, I should be able to update it for you (I think it's fairly out of date), just let me know.

Thanks @smolck that's the trick!
