### ISSUE TITLE
filename with '#' breaks externalized command line tab completion

### ISSUE THREAD

**Issue by morganmay** [vhakulinen/gnvim#171]
The IDE DrRacket (annoyingly) likes to save backups to files with names like '/home/user/#mredauto#1#', so I usually have a file in my home directory with a filename that starts with '#'. When this is the case, it breaks tab completion for filenames in gnvim's externalized command line. Instead of completing filenames, pressing `Tab` inserts tab characters. This only happens in gnvim, and only using the externalized command line. If I pass `--disable-ext-cmdline`, tab completion works as expected. Deleting the file fixes the problem, but DrRacket will just create another one before too long. I'm using gnvim v0.1.6 with nvim v0.4.4.

EDIT: I was testing various permutations of files with '#' in them, and now it doesn't seem to be causing the problem, so maybe it was something else? I'm very confused...

**Comment by vhakulinen** [comment]
I created a file with the same name, and couldn't reproduce the issue you described (I'm running the latest HEAD on both neovim and gnvim). That said, I'm tempted to guess that this could be a issue with neovim it self since its happening with externalized cmdline but not with the "native" one.

If this happens again, it would be great if you could test it with another GUI that has externalized cmdline and see what happens.

**Comment by vhakulinen** [comment]
Gnvim was rewritten from ground up for gtk4. If the problem persists, feel free to reopen this issue.
