### ISSUE TITLE
Mapping <M-;> doesn't work

### ISSUE THREAD

**Issue by muniter** [vhakulinen/gnvim#186]
Hello. Mapping <M-;> doesn't work. This is Alt-;

I use this without issue in the TUI, and also in other GUIs (fvim, goneovim). Tried launching it from the terminal and test the mapping but have no output.

What I mean by not working is that the Gui doesn't send it to neovim, meaning nothing happens.

**Comment by muniter** [comment]
Just noticed I really didn't give much information. Sorry. 

Want to add that other alt mappings work correctly, I have the issue only with this one. 

Using Linux, Arch, Wayland, SwayWM

**Comment by urxvtcd** [comment]
Same for `<Alt-=>`

**Comment by vhakulinen** [comment]
Gnvim was rewritten from ground up for gtk4, but this issue was still present. This was fixed in https://github.com/vhakulinen/gnvim/commit/6b2c8a07478f97e57de2bf8f634564c08b4cf6ad.

Regarding the `=` and `;` keys, you _might_ need to add shift key to your mappings (depending on your keyboard layout).
