### ISSUE TITLE
Could you please provide some raison d'être vis-a-vis neovim-gtk?

### ISSUE THREAD

**Issue by mcepl** [vhakulinen/gnvim#3]
It seems to me that this project targets exactly the same audience as [neovim-gtk](https://github.com/daa84/neovim-gtk/): both are in Rust built on the top of Gtk. Given neovim-gtk is older, I guess, there must be some compelling reason why you started a new project. What are the (planned) advantages over the other project? Why should I (as a possible new user) care about your project?

**Comment by vhakulinen** [comment]
The original reason was that neovim-gtk requires GTK 3.20, and I still have Ubuntu 16.04 on my work computer which has GTK 3.18 (gnvim works with GTK 3.18). Also, I've wanted to write a neovim GUI ever since the first APIs came available. This also has been (and still is) a great learning experience on both rust and GTK for me.

For advantages over neovim-gtk, currently gnvim doesn't really have any (its a bit hard to be certain since I haven't used neovim-gtk except for some quick tests). That said, I'm personally after such features that [oni](https://github.com/onivim/oni) has. If it weren't an electron app, I probably would be using it already.

Currently, gnvim has following features:

* Ligatures
* Externalized cmdline/wildmenu
* Externalized tabline
* Externalized popupmenu (with preview in the same widget, see bindings [here](https://github.com/vhakulinen/gnvim/blob/master/runtime/plugin/gnvim.vim#L54) and image [here](https://github.com/vhakulinen/gnvim/wiki))

New features that I've planned are hover information (mainly through lsp) and externalized windows and messages once those land. After that I'll probably try to do something for the status line.

So if you're after features that modern text/code editors like vscode and atom has but don't care for the whole web stack _and_ are a stubborn vim user like I am, maybe gnvim will have something to offer for you soon.

**Comment by mcepl** [comment]
It would be probably a good idea to write something like this to README.
