### ISSUE TITLE
command prompt kindof small

### ISSUE THREAD

**Issue by teto** [vhakulinen/gnvim#34]
any idea what could cause this ? https://transfer.sh/rEwDE/2019-04-26-140049_1399x948_scrot.png the prompt shows only half the height of the command ":qa"

**Comment by vhakulinen** [comment]
Did you type `:qa` manually? I've noticed some problems with the height of the command prompt on initial draw but never figured out what the problem was (something to do with gtk).

**Comment by teto** [comment]
Yes I did. I noticed afterwards that it was not systematic and most of the times the size looked ok. so not a huge deal for now.

**Comment by smolck** [comment]
Is this a bug that should be fixed in GNvim, or is it a problem with GTK?

Also, @teto the link in your original comment is now a broken (at least for me).

**Comment by vhakulinen** [comment]
Yes, this should be fixed in gnvim. It has something to do with getting the initial height for the cmdline. Similar problem exists with the cursor tooltip.

**Comment by Lythenas** [comment]
For me this problem only exists the very first time the command prompt is opened. But it is not consistent sometime it works fine the first time too.

**Comment by vhakulinen** [comment]
> For me this problem only exists the very first time the command prompt is opened. But it is not consistent sometime it works fine the first time too.

Same here.

**Comment by jaawerth** [comment]
This may or may not be related, but I'm also noticing that changing the font size with `guifont` can cause rendering issues with the cmdline that can be reset by changing cmdheight around a bit. But different font-sizes can require adjusting `cmdheight` differently... at first I thought larger fonts just needed a larger cmdheight but it seems like it's a more complicated issue than that

**Comment by smolck** [comment]
@jaawerth What’s your pango version? Sounds like #85 to me.

**Comment by jaawerth** [comment]
Ahh thanks, that looks more relevant. Apparently I went with the wrong issue ;-). I'm on 1.44.7-1.

**Comment by smolck** [comment]
No problem ;) I thought I was on track to resolving those issues in #124, but turns out I was wrong. We’ll need a proper fix, probably by supporting subpixel positioning, but that’s outside of my limited understanding of both gtk and pango. Neovim-gtk managed to fix things with https://github.com/daa84/neovim-gtk/commit/482d9c79fa0751ab50fef5d1023c8cb8c20c5e70 but I’m not sure (1) how that would apply to GNvim and (2) if that’s not masking the real problem like #124 

@jaawerth If you can offer some insight or help into a fix for #85, even if you only help with debugging, please do. GNvim is unusable for me (and I suspect other Arch/Fedora users too) because of #85 and I’d really like to fix these pango issues.

**Comment by vhakulinen** [comment]
Gnvim was rewritten from ground up for gtk4. If the problem persists, feel free to reopen this issue.
