### ISSUE TITLE
All popup menu icons are question mark icons

### ISSUE THREAD

**Issue by TypeAndProgram** [vhakulinen/gnvim#47]
From the screenshots of GNvim in the wiki I assume that there should be icons of boxes, < >, etc. in the popup menu for auto completions. However, as the title states, mine only shows circled question marks:

![image](https://user-images.githubusercontent.com/46855713/58734487-2edffe80-83bd-11e9-8f26-e5a4d3422f60.png)

Am I missing a package/font for my system? The GNvim runtime is loaded, and I have not installed GNvim; I am running it w/out installing using the `GNVIM_RUNTIME_PATH=/path/to/gnvim/runtime cargo run` command, as an FYI (although IIRC it did the same thing when it was installed on my previous Linux install).

**Comment by badosu** [comment]
This is the same for me too, I wonder if you're using a LSP plugin that is not [gnvim-lsp](https://github.com/vhakulinen/gnvim-lsp)?

I use [coc.nvim](https://github.com/neoclide/coc.nvim) and this is how it looks like:

![Screenshot from 2019-06-03 23-08-03](https://user-images.githubusercontent.com/347552/58846115-78964680-8654-11e9-9828-0036cec4d99b.png)

**Comment by TypeAndProgram** [comment]
No, I use [LanguageClient-Neovim](https://github.com/autozimu/LanguageClient-neovim). Is gnvim-lsp required to have the icons? If so, do you think that info could be added to the wiki? I’ll try switching to vim-lsp with gnvim-lsp and let you know what happens.

**Comment by TypeAndProgram** [comment]
Ok, so the problem is the language server. Using [vim-lsp](https://github.com/prabirshrestha/vim-lsp) (with or without [gnvim-lsp](https://github.com/vhakulinen/gnvim-lsp)), the icons show correctly:

![image](https://user-images.githubusercontent.com/46855713/58879355-20366780-869b-11e9-8a39-de728c2f6dbe.png)

Is there is a way to add this functionality to gnvim for other language clients like [LanguageClient-Neovim](https://github.com/autozimu/LanguageClient-neovim) as well? If not or until this is added, can this info be added to the wiki/README?

Also, could it not be set for gnvim to default to no icons in the popup menu if vim-lsp is absent?

**Comment by badosu** [comment]
> Is there is a way to add this functionality to gnvim for other language clients like LanguageClient-Neovim as well? If not or until this is added, can this info be added to the wiki/README?

Yes, it seems vim-lsp returns a `|kind|` that is specific to it, instead of a single letter as specified on `|complete-items|`.

See https://github.com/vhakulinen/gnvim/blob/master/src/ui/popupmenu/completion_item_widget.rs#L113-L147 and

> The "kind" item uses a single letter to indicate the kind of completion. This may be used to show the completion differently (different color or icon). Currently these types can be used:
>	v	variable
>	f	function or method
>	m	member of a struct or class
>	t	typedef
>	d	#define or macro

I have a diff that adds these patterns to the matching, and it works. As soon as it's polished will send a PR.

**Comment by badosu** [comment]
It seems the kind flags between lsp plugins have no standard, which can make pattern matching quite a mess:

- coc.nvim: https://github.com/neoclide/coc.nvim/blob/909710fddb04d383e5546b0f869c44f395a80d02/src/languages.ts#L143-L167
- LanguageClient-neovim: https://github.com/autozimu/LanguageClient-neovim/blob/0ac444affdff8db699684aa4cf04c2cb0daf0286/rplugin/python3/denite/lsp/protocol.py#L48-L55
- vim-lsp: https://github.com/autozimu/LanguageClient-neovim/blob/0ac444affdff8db699684aa4cf04c2cb0daf0286/rplugin/python3/denite/lsp/protocol.py#L48-L55

I think the best option is to support the case when all kinds are not matched to not display the icon, then figure out (if possible) a way to match kinds that support at these major implementations.

**Comment by vhakulinen** [comment]
First of all, I want to shout out a huge "thank you!" to @badosu for helping out with gnvim's issue tracker :raised_hands:. It really makes it easier for me to get into these issues (and PRs!) when I find the time.

As mentioned in this thread already, the icons are matched based on the `kind` in `complete-items`. Gnvim currently only knows about the `kind` values defined in the language server protocol - mainly because I used/use vim-lsp which doesn't do any mapping to values defined in vim's documentation.

Issue related to this is already opened in neovim's issue tracker: https://github.com/neovim/neovim/issues/10119. For now, the best we can do is to try find a common ground among completion providers and try to support the most shared set of `kind` values.
