### ISSUE TITLE
guifont: floating-point is not supported?

### ISSUE THREAD

**Issue by last-partizan** [vhakulinen/gnvim#65]
Hello.

Looks like floating-point numbers is not supported if font definition?

I trying to set `guifont=Monospace:h11.25`, but with no effect.
Or maybe there is another way?

**Comment by badosu** [comment]
I've never seen this use case, is this because of HiDPI display? In which case perhaps we could also fix with better support?

**Comment by last-partizan** [comment]
No, this is not HiDPI, this is some strange combination of freetype bugs (or features) and font (i'm using https://github.com/source-foundry/Hack, but it was the same with DejaVu Sans Mono)

When font-size is set to 11, somehow font height is smaller than it must be and it looks weird. When i set size to 11.25, font looks like expected.

here is what it looks like
![Screenshot from 2019-07-09 14-40-38](https://user-images.githubusercontent.com/301015/60885330-05d24980-a258-11e9-99d0-b05ba3b497d1.png)
![Screenshot from 2019-07-09 14-40-10](https://user-images.githubusercontent.com/301015/60885332-05d24980-a258-11e9-9a90-f26b01c84432.png)

**Comment by smolck** [comment]
@badosu I think the problem is in font.rs [here](https://github.com/vhakulinen/gnvim/blob/master/src/ui/font.rs#L50). It tries to parse the font to type `usize`, which doesn’t support floating-point numbers and thus fails. A fairly easy fix, I think: just swap the font height in the `Font` struct to an `f32` or similar and parse it to that floating-point type instead (and make other changes elsewhere to accommodate that change accordingly). If we want I can make a PR for it, though @vhakulinen might just want to do the commit, since I think it’d be fairly small. (All this is assuming that `f32` would work, haven’t tested it/investigated. Let me know if I’m wrong on any of this.)

**Comment by badosu** [comment]
@smolck Like the `WM_CLASS` commit I think it's better to send PRs. It gives a single point of discussion and I can simply go grab your fork and test it.

**Comment by smolck** [comment]
@last-partizan As of #66, GNvim now supports floating-point guifont height.
