### ISSUE TITLE
Invalid popupmenu position

### ISSUE THREAD

**Issue by last-partizan** [vhakulinen/gnvim#69]
One more issue stopping me from using gnvim.

popupmenu is not in the right place
![Screenshot from 2019-07-11 17-39-34](https://user-images.githubusercontent.com/301015/61060361-12df6c00-a403-11e9-92df-84019fbee46c.png)

At first I was using neovim 0.3.8, and Readme says gnvim requires latest master, so i installed latest neovim-git. No luck, popupmenu is still few lines lower than expected.

Even with empty vimrc.

BTW, `gnvim -- u NONE` is not showing popupmenu at all. With `gnvim -- -u /dev/null` menu is displayed, but not in the right place)

```
> yay -Q gnvim-git neovim-git gtk3 rust
gnvim-git r219.9ea48e9-1
neovim-git 0.3.4.r1258.g6eab3b925-1
gtk3 1:3.24.10-1
rust 1:1.35.0-1
```

**Comment by smolck** [comment]
@last-partizan I am unable to reproduce this. Were you getting this when using Neovim 0.3.8? GNvim should support Neovim 0.3.8, so no need to use a different version (I use neovim-nightly with no problems, which is newer). We should update the README to be more clear on that.

When you run GNvim like you normally would, what is the output of `:echo g:gnvim_runtime_loaded`?


Can you try the following and see if the problem still occurs (I think gnvim-git is about 2 months outdated)?
 ```
$ git clone https://github.com/vhakulinen/gnvim
$ cd gnvim
$ GNVIM_RUNTIME_PATH=<absolute directory to gnvim/runtime> cargo run
```
To clarify, you have to give GNvim the absolute directory to the `runtime` folder in its directory, i.e. if its in ~/Downloads/gnvim, run `$ GNVIM_RUNTIME_PATH=$HOME/<your username>/Downloads/gnvim/runtime cargo run`

> BTW, gnvim -- u NONE is not showing popupmenu at all.

Using `gnvim -- -u NONE` prevents GNvim from loading its runtime files, so that's probably why the popupmenu doesn't show up.

**Comment by last-partizan** [comment]
```
> echo g:gnvim_runtime_loaded
1
```

My gnvim-git is using this branch https://github.com/smolck/gnvim/commits/support-floating-point-guifont-height until it is merged.

With `GNVIM_RUNTIME_PATH=/home/serg/work/git/gnvim/runtime cargo run` completemenu position is still not correct.

Looks like it becouse of wayland. On xorg session menu position is correct.

**Comment by smolck** [comment]
Interesting. Would you be able to test and see if this issue occurs with [neovim-gtk](https://github.com/daa84/neovim-gtk)? It could be a GTK problem, in which case we may have to find a workaround (if there is one).

**Comment by last-partizan** [comment]
neovim-gtk has no such problem

![Screenshot from 2019-07-11 19-10-52](https://user-images.githubusercontent.com/301015/61067198-adde4300-a40f-11e9-9c83-013a392a644c.png)

**Comment by badosu** [comment]
> @badosu CC: Are you able to reproduce this?

Nope.

Perhaps wayland is giving different dimensions when calculating the anchor position? (https://github.com/smolck/gnvim/blob/9ea48e92fab0730b1530ce4145fb76be49332635/src/ui/popupmenu/popupmenu.rs#L207-L219)

Unfortunately I use (f*ck you) nvidia and can't test.

**Comment by smolck** [comment]
Just switched over to using wayland/sway from xorg/i3-gaps, and I still can't reproduce this issue, so I don't think it's a wayland problem. Any other ideas?

**Comment by last-partizan** [comment]
I just checked it under sway, menu position is correct.

I'm using gnome/wayland, and bug also is reproducible under weston.

**Comment by badosu** [comment]
Well, one idea is to add `dbg!(x)\ndbg!(y)\ndbg!(width)\ndbg!(height)` [here](https://github.com/smolck/gnvim/blob/9ea48e92fab0730b1530ce4145fb76be49332635/src/ui/popupmenu/popupmenu.rs#L220) so we can check if it's some issue calculating the anchor or if gtk itself is behaving weird.

**Comment by smolck** [comment]
Output when typing /usr/ is essentially this on sway:
```
x = 63
y = 19
width = 430
height = 500
```

**Comment by last-partizan** [comment]
My results, typing `/`

sway:
```
x = 33
y = 23
width = 430
height = 500
```

gnome:
```
x = 59
y = 83
width = 430
height = 500
```

**Comment by last-partizan** [comment]
Also, added `dbg!(pos)`

sway
```
[src/ui/popupmenu/popupmenu.rs:209] pos = Rectangle {
    x: 33,
    y: 0,
    width: 11,
    height: 23,
}
```

gnome
```
[src/ui/popupmenu/popupmenu.rs:209] pos = Rectangle {
    x: 59,
    y: 60,
    width: 11,
    height: 23,
}
```

**Comment by badosu** [comment]
Long shot, and my last speculation on this matter since I can't test it. Perhaps this is a scaling issue where the calculation returns a value with a certain DPI and another with a different one?

**Comment by smolck** [comment]
When you use gnome, if you run `cargo test` in the gnvim directory, do any of the tests fail (namely, the `get_preferred_*` ones)?

**Comment by last-partizan** [comment]
test result: ok. 68 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

**Comment by last-partizan** [comment]
Here is some more debugging, i was trying to dig where from incorrect values comes from.
Since i was triggering popupmenu on first line, i expect y to be 0.
And it becomes incorrect after translate_coordinates.
If i remove translate_coordinates, menu is in right place (but only if there is no tabs, with tabs it's under tab)
 
```
[src/ui/grid/grid.rs:158] render::get_coords(ctx.cell_metrics.height, ctx.cell_metrics.width,
                   row as f64, col as f64) = (
    33.0,
    0.0,
)
[src/ui/grid/grid.rs:165] self.eb.translate_coordinates(&self.eb.get_toplevel().unwrap(), x as i32,
                              y as i32).unwrap() = (
    59,
    60,
)
[src/ui/ui.rs:687] rect = Rectangle {
    x: 59,
    y: 60,
    width: 11,
    height: 23,
}
```

**Comment by smolck** [comment]
@last-partizan Nice work, that narrows things down a bunch! That is a strange bug. `y` goes from being 0.0 to 60, in one function call ([and it's a gtk-rs function](https://gtk-rs.org/docs/gtk/trait.WidgetExt.html#tymethod.translate_coordinates)). Maybe there's an alternative to that function? I'll look into it and see if I can find a possible workaround. It definitely seems like a bug in gtk-rs itself, not GNvim (although I could be wrong).

**Comment by smolck** [comment]
@last-partizan This is only a temporary fix until we figure this out, but it may work. Try running gnvim with `gnvim --disable-ext-tabline`/`cargo run -- --disable-ext-tabline`, and with this diff:
```diff
diff --git a/src/ui/grid/grid.rs b/src/ui/grid/grid.rs
index b2e61b4..e6c0d63 100644
--- a/src/ui/grid/grid.rs
+++ b/src/ui/grid/grid.rs
@@ -162,18 +162,9 @@ impl Grid {
             col as f64,
         );

-        let (x, y) = self
-            .eb
-            .translate_coordinates(
-                &self.eb.get_toplevel().unwrap(),
-                x as i32,
-                y as i32,
-            )
-            .unwrap();
-
         gtk::Rectangle {try it
-            x,
-            y,
+            x: x as i32,
+            y: y as i32,
             width: ctx.cell_metrics.width as i32,
             height: ctx.cell_metrics.height as i32,
         }
```

Running gnvim with `--disable-ext-tabline` will, as you'd expect, disable the external tabline (not sure if that's a deal breaker for you; it will use the same tabline as the TUI does w/your config), but it _should_ fix your problem (although I can't be sure since I can't test it).

Quite a long shot I think, but you could also try this diff (I _really_ doubt this will work, but might as well throw it out there since I can't test it):
```diff
diff --git a/src/ui/grid/grid.rs b/src/ui/grid/grid.rs
index b2e61b4..bebe3cc 100644
--- a/src/ui/grid/grid.rs
+++ b/src/ui/grid/grid.rs
@@ -163,9 +163,9 @@ impl Grid {
         );

         let (x, y) = self
-            .eb
+            .da
             .translate_coordinates(
-                &self.eb.get_toplevel().unwrap(),
+                &self.da.get_toplevel().unwrap(),
                 x as i32,
                 y as i32,
             )
```

**Comment by last-partizan** [comment]
First diff is exactly what i tried, and with `disable-ext-tabline` it works as expected - menu is in the right place.
Second diff makes no difference.

**Comment by vhakulinen** [comment]
If disabling the ext_tabline helps, maybe there is something wrong with how gnvim currently has the widget structure. Currently, we need to [offset the popupmenu by tabline's height](https://github.com/vhakulinen/gnvim/blob/233b9cff98c4d06041de1a5fe27e201ebc686559/src/ui/ui.rs#L684-L685). Would be interesting to see what the `extra_h` value is when the popupmenu has invalid position.

**Comment by last-partizan** [comment]
Disabling ext_tabline helps only without translate_coordinates. In normal build popupmenu is still has incorrect position.

extra_h is 0 without tabs abd 38 with tabs.
with disable-ext-tabline in both cases extra_h is 0

**Comment by smolck** [comment]
The offset is not the problem in this case I don't think. It seems that after the call to `translate_coordinates`, the y isn't translated properly with gnome/wayland (it goes from 0 to 60, which should at most be 0 to 38 if tabs are shown, as 38 is the height of the tabline). Thus, after the popupmenu is offset by the height of the tabline, some extra height still remains in rect.y that shouldn't, and that's where the problem comes from (the extra height makes the popupmenu lower).

**Comment by smolck** [comment]
@last-partizan You can try [this branch](https://github.com/smolck/gnvim/tree/update-dependencies), but unfortunately I don't think it will fix your problem. It may be a GTK issue, but I'm not sure since it doesn't happen in neovim-gtk (and if it still happens in the latest version, it seems unlikely that it is a GTK bug)

@vhakulinen We may be able to find a workaround that doesn't use `translate_coordinates`, but I'm not sure if that's something we should do. What do you think?

**Comment by last-partizan** [comment]
I just compiled branch `update-dependencies` and it does not fixed issue.

BTW, i don't see any calls to translate_coordinates in neovim-gtk, probably this is why it does not have this problem.

**Comment by vhakulinen** [comment]
@last-partizan which gtk version are you using?

@smolck I wouldn't remove the `translate_coordinates` call before we understand why its giving a different result. Btw, that code was introduced here: https://github.com/vhakulinen/gnvim/commit/afeee13d4fd643185dcd513712deed4cd1e5b4e0.

> BTW, i don't see any calls to translate_coordinates in neovim-gtk, probably this is why it does not have this problem.

Thats because neovim-gtk is using `GtkPopover` to display the popupmenu.

To me, it looks like the x values is invalid too.

**Comment by last-partizan** [comment]
@vhakulinen i'm usign `gtk3 1:3.24.10-1`

yes, x values also invalid.

**Comment by vhakulinen** [comment]
Do you have any UI scaling enabled in your DE/WM?

**Comment by last-partizan** [comment]
@vhakulinen i don't have any on desktop, and have text-scaling enabled (#79) on laptop.

On both machines menu position is incorrect and both is using wayland/gnome.

**Comment by vhakulinen** [comment]
Fixed.

**Comment by last-partizan** [comment]
Thanks, now it is working as expected.
