### ISSUE TITLE
Show current directory as part of title

### ISSUE THREAD

**Issue by bkjohnson** [vhakulinen/gnvim#73]
Having the title always be a static `Neovim` makes it dificult to know where you are when alt-tabbing between multiple `gnvim` windows.  It would be nice If the title could be something like `Neovim - your/current/dir`.

I've never used rust so I was a bit hesitant about opening a PR, but I did this locally and got what I was looking for:

```diff
diff --git a/src/ui/ui.rs b/src/ui/ui.rs
index 6285d46..6ad3b57 100644
--- a/src/ui/ui.rs
+++ b/src/ui/ui.rs
@@ -1,4 +1,5 @@
 use std::collections::HashMap;
+use std::env;
 use std::sync::mpsc::{Receiver, RecvTimeoutError};
 use std::sync::{Arc, Mutex};
 use std::thread;
Stage this hunk [y,n,q,a,d,j,J,g,/,e,?]? n
@@ -103,7 +104,8 @@ impl UI {
     ) -> Self {
         // Create the main window.
         let window = gtk::ApplicationWindow::new(app);
-        window.set_title("Neovim");
+        let path = env::current_dir().unwrap();
+        window.set_title(format!("Neovim - {}",  path.display()).as_str());
         window.set_default_size(1280, 720);
 
```

Is there any guidance on where this would need to be in order to update the directory portion of the title anytime the user changes working directory?

**Comment by smolck** [comment]
I like this idea! Never really noticed it said `Neovim` (which should probably be `GNvim`). It seems that putting it in ui.rs (specifically in the `handle_redraw_event` function's match arm for `RedrawEvent::GridCursorGoto`) would work:
```diff
diff --git a/src/ui/ui.rs b/src/ui/ui.rs
index 6285d46..8d07b11 100644
--- a/src/ui/ui.rs
+++ b/src/ui/ui.rs
@@ -529,6 +529,12 @@ fn handle_redraw_event(
 
                 // And after all that, set the current grid's cursor position.
                 grid.cursor_goto(*row, *col);
+
+                let mut nvim = nvim.lock().unwrap();
+                window.set_title(format!("GNvim - {}",
+                                         nvim.command_output("pwd")
+                                             .unwrap_or(String::from("")))
+                                 .as_str());
             }
             RedrawEvent::GridResize(grid, width, height) => {
                 let grid = state.grids.get(grid).unwrap();
```

This works fairly well (every time you change to a different nvim grid, i.e. window/tab/etc., it updates the window title), but I'm not sure this is how we should/want to do this (if so, we'd need to polish it just a bit, mostly to handle if the command fails; just default to 'GNvim' as the window title if so).

As a side note, using `env::current_dir().unwrap()` wouldn't work properly because it seems (to me, at least) to track the directory of your terminal, not your Neovim window/tab/etc. that you are currently working in; using the neovim-lib `command_output` method and the `pwd` nvim command to get the current working directory gives what I think is the functionality you're looking for.

**Comment by bkjohnson** [comment]
Updating the title in `RedrawEvent::GridCursorGoto` definitely seems like it's more on the right track.

And I did a bit of looking as well and couldn't figure out how to get the output from the async call. :thinking:

**Comment by vhakulinen** [comment]
Use `titlestring` to set window title (`:h titlestring`). You could try `:set titlestring=Neovim\ --\ %{expand(\"%:~:.:h\")}`

**Comment by smolck** [comment]
@vhakulinen Nice, didn't know that was a feature! One more thing though: GNvim still has `NVIM` at the end of the title. The following diff makes it to where it ends in `GNVIM` instead, which IMHO is more suiting, since the application is `GNvim` after all:
```diff
diff --git a/src/ui/ui.rs b/src/ui/ui.rs
index 6285d46..dc1c16e 100644
--- a/src/ui/ui.rs
+++ b/src/ui/ui.rs
@@ -498,7 +498,7 @@ fn handle_redraw_event(
     for event in events {
         match event {
             RedrawEvent::SetTitle(title) => {
-                window.set_title(title);
+                window.set_title(title.replace("NVIM", "GNVIM").as_str());
             }
             RedrawEvent::GridLine(lines) => {
                 for line in lines {
```
We could also make it replace `NVIM` with `GNvim` instead of all caps.

@bkjohnson Note that you have to put `set title` in your `.vimrc` (or just use `:set title` in nvim) in order for `set titlestring=` to work. However, with only `set title` I think you'll get the functionality your looking for.

**Comment by vhakulinen** [comment]
We could set the default title in the gnvim runtime files.

**Comment by bkjohnson** [comment]
Thank you both, I've added this to my `.vimrc` and it is useful enough:

```vim
autocmd BufEnter * let &titlestring = expand("%:~:.:.:h")
set title
```
