### ISSUE TITLE
Text scaling is not respected

### ISSUE THREAD

**Issue by last-partizan** [vhakulinen/gnvim#79]
On my laptop i'm using
```
gsettings set org.gnome.desktop.interface text-scaling-factor 1.3
```

And looks like gnvim ignores it, not completely, only for text window.
Popupmenu, command line and tabline has correct font size.

Here is how it looks.
![Screenshot from 2019-07-18 19-29-49](https://user-images.githubusercontent.com/301015/61475169-e1cae280-a992-11e9-8286-bd3dd0b442f8.png)
![Screenshot from 2019-07-18 19-28-53](https://user-images.githubusercontent.com/301015/61475171-e2637900-a992-11e9-9be2-5bb07ca8962e.png)

**Comment by badosu** [comment]
As far as I can see we use GTK components for the UI but cairo and pango directly for rendering the grid, so that's probably why this happens.

This is the line that sets the size of the font:

https://github.com/smolck/gnvim/blob/a8a6ee9ae38aef5e4fb2cc02679f7952eda9392d/src/ui/font.rs#L92-L94

`pango::SCALE` is an integer not respecting the text scaling configuration.

It seems both [pango](https://gtk-rs.org/docs/pango/struct.Attribute.html#method.new_scale) and [cairo](https://gtk-rs.org/docs/cairo/struct.Context.html#method.set_scaled_font) accept scale factors though a reliable and cross-platform method for retrieving this value should be considered.

**Comment by vhakulinen** [comment]
I did struggle with the font scaling quite a bit and eventually gave up on it.

> It seems both pango and cairo accept scale factors though a reliable and cross-platform method for retrieving this value should be considered.

I actually wasn't aware of those functions. I would imagine that, since gnvim is using gtk, there would be some decent way to acquire those scale numbers through the gtk API.

**Comment by vhakulinen** [comment]
Can you try #89?

**Comment by last-partizan** [comment]
@vhakulinen yes, now it is working as expected.

**Comment by vhakulinen** [comment]
Fixed in https://github.com/vhakulinen/gnvim/commit/3a5e49e18c96814e038a885e705c1d3be48d8df5
