### ISSUE TITLE
Building instructions for macOS?

### ISSUE THREAD

**Issue by kropper** [vhakulinen/gnvim#8]
I'd love to try this out.

Is webkit2gtk-sys available somehow on macOS? It can't be installed via Homebrew and the link on "building on other systems" does not cover macOS either.

```
error: failed to run custom build command for `webkit2gtk-sys v0.7.0` 
--- stderr
`"pkg-config" "--libs" "--cflags" "webkit2gtk-4.0 >= 2.14"` did not exit successfully: exit code: 1
--- stderr
Package webkit2gtk-4.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `webkit2gtk-4.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'webkit2gtk-4.0' found

warning: build failed, waiting for other jobs to finish...
error: build failed                                                                                                                                                             
GNVIM_RUNTIME_PATH=./runtime cargo run 
```

**Comment by vhakulinen** [comment]
Hi! Unfortunately there is currently no easy way to get `libwebkitgtk` on macos. This came as a surprise for me too just the other day when someone was asking about this over gitter.

There used to be an homebrew formula but it got [graveyarded](https://github.com/Homebrew/homebrew-core/pull/9053) because nobody were up to maintaining it (because it required some patches on macos). There [seems](https://github.com/astroidmail/homebrew-astroid/blob/master/Formula/webkitgtk%402.4.11.rb) to be some formula still by application named `astroidmail` but that formula status is a bit [unclear](https://github.com/astroidmail/homebrew-astroid/issues/11).

I asked about this on the webkitgtk IRC and they basically said that they are limited on man power to support other platforms than linux currently (tho' it looks like webkitgtk compiles and works on windows). If someone has time, I'd suggest digging up the old formulas for older version of webkitgtk and see if there are any patches that were required (or other shenanigans) and try to port them to newer version of webkitgtk. I don't have access to a mac machine so I really cant do this.

**Comment by jangid** [comment]
In this thread, in the end there are instructions for building webkit2gtk - https://www.reddit.com/r/rust/comments/7tcifu/problems_with_webkit2gtkrs_with_macos/

**Comment by vhakulinen** [comment]
Can someone confirm that gnvim builds (and works) on mac (without the cursor tooltip)?

**Comment by adaszko** [comment]
It builds and it works!  Although I think the macOS build instructions could include the command to start it, i.e. `cargo run --no-default-features` worked for me.

![image](https://user-images.githubusercontent.com/165678/65859365-4974b500-e368-11e9-90cd-c455d5ab5ef1.png)
