### ISSUE TITLE
Initial grid size is too small

### ISSUE THREAD

**Issue by YaLTeR** [vhakulinen/gnvim#82]
I use the `sway` Wayland compositor. When I initially open `gnvim`, the grid size is smaller than the actual window size, and I need to resize it for it to fix itself.

Right after opening:
![image](https://user-images.githubusercontent.com/1794388/61650413-86397700-ac68-11e9-92ab-a0bdeedd0c16.png)

After resizing to fix the issue:
![image](https://user-images.githubusercontent.com/1794388/61650436-92bdcf80-ac68-11e9-85dd-d1d0c049dd34.png)

This also happens with smaller window sizes:
![image](https://user-images.githubusercontent.com/1794388/61650522-c39e0480-ac68-11e9-93f0-661fdc79058e.png)

**Comment by smolck** [comment]
I was previously going to open an issue on this topic, but after working on #78 I think I know what the problem is. GNvim isn't handling each redraw event when given multiple at once, and so when given multiple (on opening the window) events for drawing the window, it doesn't execute them all, and (I think) this causes the problem.

Here is a (temp, not for permanent usage) fix in a gist if you want to try it out. It should fix your problem if my speculations are correct: https://gist.github.com/smolck/5d92207475933b081d990b73b6a3a586

**Comment by badosu** [comment]
I confirm seeing this issue though not easily reproducible.

**Comment by smolck** [comment]
For me this doesn't happen when using `cargo run`. @badosu Can you confirm this?

**Comment by badosu** [comment]
This is with i3 (can't use sway due to a certain GPU brand laziness), just tested.

Opening as a new split:

![Screenshot from 2019-07-22 14-50-15](https://user-images.githubusercontent.com/347552/61653220-2fe02e80-ac90-11e9-98e5-884d735d3f7e.png)

Moving the splits and forcing a redraw:

![Screenshot from 2019-07-22 14-50-37](https://user-images.githubusercontent.com/347552/61653236-3c648700-ac90-11e9-852f-82e1cc6e85a5.png)

**Comment by smolck** [comment]
This may actually be a bug with Neovim (I'm using neovim-nightly from the AUR). I use termite, which supports the `-e` option to run something on opening the terminal. Running Neovim on startup of termite with `$ termite -e nvim` causes the same problem to occur:

![image](https://user-images.githubusercontent.com/46855713/61653939-079d0380-ac81-11e9-883d-4eeb76990307.png)

**Comment by YaLTeR** [comment]
For me `alacritty -e nvim` works correctly.

**Comment by smolck** [comment]
I am able to make this issue happen with `cargo run` when I comment out this line in ui.rs: https://github.com/vhakulinen/gnvim/blob/1d8a0425b851cd4cb821c38ac2b6a50c6b52fd07/src/ui/ui.rs#L107

**Comment by vhakulinen** [comment]
I've encountered the same problem, and its rather annoying. @smolck if you can produce this with TUI, you should open a bug report on neovim's repo.

**Comment by bfredl** [comment]
Not sure if it is causing this particular issue, but there is a slight inefficiency in gnvim's initialization. First neovim is attached with fixed size `nvim.ui_attach(80, 30, &ui_opts)`, and immediately after that, when the drawing area is realized, the true initial size is set by  `nvim.ui_try_resize_async` in the first drawing area resize event. It would be better to delay attachment until the initial size is known.

**Comment by smolck** [comment]
> @smolck if you can produce this with TUI, you should open a bug report on neovim's repo.

It may be (and probably is) a Termite bug: https://github.com/thestinger/termite/issues/686#issue-461756403

**Comment by smolck** [comment]
After throwing a `dbg!(&args)` [here in nvim_bridge/mod.rs](https://github.com/vhakulinen/gnvim/blob/master/src/nvim_bridge/mod.rs#L595) and looking at the output, when this bug happens GNvim is only getting a single (when I tested it) `grid_resize` event from Neovim, with the wrong width and height. Not sure why that is happening? If I get the chance I'll throw some dbg!'s around neovim-gtk to see what events it receives.

**Comment by smolck** [comment]
@vhakulinen @badosu After some testing, GNvim doesn’t get the right values in the `grid_resize` events from Neovim on startup (i.e. it gets different width and height vals from those it gets when forced to redraw/resize the grid), so the grid doesn’t fill the window on initial draw (I think it redraws correctly for the width and height that it is given though). Any ideas of what could cause that? Bfredl mentioned above that GNvim is inefficient in attaching the UI, but could that really be the cause? It seems slight enough that it couldn’t cause this issue, but IDK.

As a side note, neovim-gtk delays the UI attachment as necessary, removing that inefficiency. However, it may require a decently-sized refactor, and I’m not sure how high of a priority adding the necessary code is (unless it’s causing this problem, which I don’t think I can test very easily ATM). For now, I can try to get a working branch where the UI attachment is delayed until the drawing area is realized to test if that slight inefficiency is the issue.

**Comment by bfredl** [comment]
I'm not sure if it needs to be a big refractor. You can still create/connect the nvim instance in the same place. What is needed is a flag to indicate if ui_attach is called yet, and then the gtk resize  handler should call it the first time instead of ui_try_resize and change the flag.

It would at least fix issues with error messages in `init.vim` being drawn properly.

**Comment by smolck** [comment]
@YaLTeR could you try out #86's branch (https://github.com/smolck/gnvim/tree/fix-ui-attach-inefficiency) and see if that fixes this issue for you?

**Comment by YaLTeR** [comment]
It does start with the correct size, but with a small graphical flicker before and also scrolled a couple of lines down.

**Comment by smolck** [comment]
> . . . but with a small graphical flicker before . . .

I may be wrong but I think that was already there. #86 may make it more noticeable though, so we may want to look into ways of removing the flicker if that's possible.

> . . . and also scrolled a couple of lines down.

@YaLTeR Not sure I can reproduce this. Do you mean your cursor is on a different line from the first one, or something else?

**Comment by YaLTeR** [comment]
Well, I use the Startify plugin which provides a start screen, and this is how it looks on start:
![image](https://user-images.githubusercontent.com/1794388/62267560-55341180-b3e1-11e9-93e1-6fc7e21f7a28.png)
as opposed to:
![image](https://user-images.githubusercontent.com/1794388/62267564-59602f00-b3e1-11e9-842b-7361cd216134.png)

**Comment by smolck** [comment]
I can reproduce it using Startify, and I was able to position it correctly by scrolling up with the mouse wheel; I wonder why it starts scrolled downwards? It seems to only happen with Startify, not when opening a file from gnvim via `$ gnvim <filename>`.

**Comment by smolck** [comment]
@vhakulinen @badosu Is there a way we could optimize/change how GNvim is drawn initially? Ideally we'd only call `window.show_all()` after everything's loaded "behind the scenes", but is that possible? (Alternatively, maybe we could change when and in what order everything's drawn?) It seems drawing GNvim initially is a bit finicky (e.g. using `ui.win.borrow().show_all()` [here](https://github.com/vhakulinen/gnvim/blob/1d8a0425b851cd4cb821c38ac2b6a50c6b52fd07/src/ui/ui.rs#L308) instead of `window.show_all()` [here](https://github.com/vhakulinen/gnvim/blob/1d8a0425b851cd4cb821c38ac2b6a50c6b52fd07/src/ui/ui.rs#L273) doesn't draw things correctly).

**Comment by badosu** [comment]
@smolck I've not had too much time lately, but will try to take a look at this issue this week.

By the way, I tested the latest master and the issue persists with the gap on the bottom part when opening gnvim with a split on i3. The UI loads much snappier now though, so definitely an improvement, good job!

**Comment by smolck** [comment]
@badosu Okay, and thanks! 

> By the way, I tested the latest master and the issue persists . . .

Just so I am certain, when you say latest master, you mean you tried my branch, right? Strange; it fixes my problem on AwesomeWM. I’ll have to start up i3 & Sway and see if I get the same result as you.

Currently (I think, may be wrong here) when the grid size changes (the window resizes) GNvim tells Neovim to resize itself, which in turn causes GNvim to handle the `grid_resize` event that Neovim sends after we call `ui_try_resize_async`. The grid size problem may have something to do with this indirect resizing, but I’m not certain. [See here for what I’m talking about](https://github.com/vhakulinen/gnvim/blob/d4d9d93acf6698ab40b0d26e1093e739940ac7f8/src/ui/ui.rs#L142).

**Comment by badosu** [comment]
> Just so I am certain, when you say latest master, you mean you tried my branch, right?

Ah, thought it was already merged. Tested and it's fixed :clap:
