### ISSUE TITLE
Support input piping

### ISSUE THREAD

**Issue by yodahuang** [vhakulinen/gnvim#83]
Currently, 
```
echo "foo" | gnvim
```
yields a blank document, while
```
echo "foo" | gnvim -
```
returns an error saying `thread 'main' panicked at 'Error sending message: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:999:5`

It would be nice if we could have input piping / reading from stdin work properly.

**Comment by smolck** [comment]
Something along these lines (though more polished: not just blindly unwrapping, not causing infinite loop if no input, etc.) would probably work (it does get the piped info):
```rust
    let stdin = std::io::stdin();
    for line in stdin.lock().lines() {
        // Pseudocode
        neovim_println!("{}", line);
    }
```
There's probably a better way, but even if that's the case we still need a way to push the text to the starting neovim buffer, which I'm not sure how to do ATM (`neovim_println!` isn't actually a thing unfortunately).

**Comment by bfredl** [comment]
As it happens, we are planning to add nvim core support for this. Because with https://github.com/neovim/neovim/pull/10071 even TUI will use the "remote UI" protocol. Probably we will allow `nvim --embed` to take an extra fd (like fd=3), and some API function `nvim_load_stdin(fd)` (to be called before ui_attach) to ask nvim to load the "stdin file" from this fd instead.

**Comment by vhakulinen** [comment]
Supported now on unix targets.
