### ISSUE TITLE
Fuzzy text

### ISSUE THREAD

**Issue by elihunter173** [vhakulinen/gnvim#91]
Certain motions (I notice it most with `{` and `}`) make text look really fuzzy. It seems to be more intense as the lines get further way from the cursor.

The fuzziness does not go away until I move my cursor over those lines again, but sometimes even that does not work.

![image](https://user-images.githubusercontent.com/42009212/62829024-2298ce80-bbc2-11e9-86b3-9ba7a4afa57e.png)

**Comment by smolck** [comment]
What pango version are you using? If you’re using pango v1.44, could you try downgrading to 1.43 and see if you still have this issue? There are issues with GNvim and the latest pango version ATM (see #84), and so that could be the problem if you’re using pango v1.44 (of course that’s just speculation).

**Comment by vhakulinen** [comment]
Likely a issue with pango v1.44. Check your pango version as @smolck suggested.

**Comment by elihunter173** [comment]
I was using pango v1.44 and downgrading to pango v1.43 does fix the issue.

**Comment by elihunter173** [comment]
Playing around with the issue more, there are also thin horizontal lines on line breaks occasionally.

**Comment by smolck** [comment]
Almost definitely a pango issue (I can reproduce with pango 1.44.3):

![image](https://user-images.githubusercontent.com/46855713/62834888-c95b8a00-bc17-11e9-8311-7d725a890261.png)

@vhakulinen @badosu Any ideas on how we could fix these pango issues? They break GNvim in multiple ways, ways that I think would cause people not to use GNvim (they render it fairly unusable). We know that the problem isn't subpixel positioning, since [pango now defaults to rounding like it previously did](https://gitlab.gnome.org/GNOME/pango/commit/77b78746c901f95ca45a9ccffe9c32a38c0fb32b), so we'll have to keep looking.

Nice thing is that users with Ubuntu-based distros who aren't on the bleeding edge of things won't see these issues until Ubuntu or their distro upgrades the pango version in their repos, so that will give us time to fix these issues (meanwhile Arch users like myself need to downgrade pango to use GNvim).

**Comment by smolck** [comment]
> Playing around with the issue more, there are also thin horizontal lines on line breaks occasionally.

@elihunter173 I see those too (they seem to lessen after opening the [external] cmdline though). Also, parentheses are misplaced too close to the left, as are periods and commas.

**Comment by vhakulinen** [comment]
Duplicate of #84.
