### ISSUE TITLE
Improve CLI usage errors to hint about nvim vs. gnvim flags

### ISSUE THREAD

**Issue by dbarnett** [vhakulinen/gnvim#99]
vim and neovim support a few flags for opening multiple files, `-d` for opening in side-by-side diff mode, `-o`/`-O` for opening multiple windows stacked vertically/horizontally, `-p` to open in multiple tabs, etc. gnvim supports opening splits and diffs from within nvim after starting it, but doesn't support those multiple-file options. If I try to pass flags like that when launching gnvim, I get errors like `error: Found argument '-d' which wasn't expected, or isn't valid in this context`.

Is it intentional not to support those flags, or could they be added?

**Comment by smolck** [comment]
GNvim does support those commands; you just have to pass them to nvim, not GNvim, using `$ gnvim -- -<nvim option>`. Try running those commands like this:
```
$ gnvim -- -d <file1> <file2>
$ gnvim -- -o <file1> <file2>
```

The double dash is used to pass args to nvim; run `gnvim --help` for more info.

**Comment by dbarnett** [comment]
Thanks, that does what I wanted!

I see now the subtle hint about how args are handled in the usage line `gnvim [FLAGS] [OPTIONS] [FILES]... [-- <ARGS>...]`. FWIW I would have figured it out on my own if the error a little more self-explanatory, like
```
$ gnvim -d file1 file2 
error: Found argument '-d' which wasn't expected, or isn't valid in this context. If this is an argument for nvim, try moving it after a -- separator.

USAGE:
    gnvim [GNVIM_FLAGS] [OPTIONS] [FILES]... [-- <NVIM_ARGS>...]

For more information try --help
```

**Comment by smolck** [comment]
> FWIW I would have figured it out on my own if the error a little more self-explanatory, like . . .

Thanks for the info, I'll get a PR for this when I get the chance (unless someone else does it first).

**Comment by dbarnett** [comment]
Sure thing, thanks!

And BTW one reason I've been going out of my way to report minor issues is I'm interested in eventually getting comfortable with Rust and contributing, so I'm poking around for things that bug me that I could solve. Hope it's not a nuisance. So far I'm somewhat interested in #70 which I'm running into on my Pixelbook, and possibly scrollbars and multigrid (#25). I'd also love to get some fancy navigation features like GUI menus, a [minimap](https://atom.io/packages/minimap), or marking placed signs directly on the scrollbar, but I'm getting the impression that gnvim specifically strives to _not_ get fancy and might discourage adding those kinds of features.

**Comment by smolck** [comment]
> And BTW one reason I've been going out of my way to report minor issues is I'm interested in eventually getting comfortable with Rust and contributing, so I'm poking around for things that bug me that I could solve. Hope it's not a nuisance. 

Thank you! Your helping to improve GNvim, which is certainly not a nuisance. The fix for this issue here may be a bit more involved than I figured at the first, but if you want to take a stab at it then please do!

> I'd also love to get some fancy navigation features like GUI menus, a minimap, or marking placed signs directly on the scrollbar, but I'm getting the impression that gnvim specifically strives to not get fancy and might discourage adding those kinds of features.

GNvim, from my perspective, strives to _enhance Neovim_ in a way that _isn't possible with a terminal_; therefore, things that contribute to that (scrollbars, minimaps, GUI file browser, etc.) will likely not be discouraged, so long as they keep the Vim-centric feeling (i.e. everything should be keyboard navigable and such). See https://github.com/vhakulinen/gnvim/issues/75#issuecomment-513877872 for my feelings concerning this (see the whole thread if you want more info). At the end of the day, our goal (AFAIK, being a contributor and not the author of the project) is not to make an IDE, but a GUI frontend for Neovim that improves its user experience.

**Comment by badosu** [comment]
> And BTW one reason I've been going out of my way to report minor issues is I'm interested in eventually getting comfortable with Rust and contributing, so I'm poking around for things that bug me that I could solve.

Happy to hear that! When I started submitting a few patches I did not know anything about Rust and I started picking up as I went.

If you want to try and play with it (it would be a good first issue), this is the relevant section: https://github.com/vhakulinen/gnvim/blob/68e3fc8d2e8f6f7bbdd73641b00031c16004e8cc/src/main.rs#L89-L111

Notice the comments on top of the arguments are used to serialize the message.

**Comment by smolck** [comment]
After looking into this, I may open an issue on the `structopt` project, since AFAIK the error message when a bad argument is passed isn’t configurable via the crate, which makes fixing this issue more involved.

**Comment by vhakulinen** [comment]
> I'd also love to get some fancy navigation features like GUI menus, a minimap, or marking placed signs directly on the scrollbar, but I'm getting the impression that gnvim specifically strives to not get fancy and might discourage adding those kinds of features.

I definitely want to have fancy GUI features, but in a way that it they stay true to nvim[1]. Multigrid is already in progress in #95, which is semi requirement for scroll bars. Marking sings directly to the scroll bar shouldn't be too big of a thing, since afaik you can get required information for that from nvim without needing any special APIs.

> And BTW one reason I've been going out of my way to report minor issues is I'm interested in eventually getting comfortable with Rust and contributing...

Please, go for it! Any help is appreciated. I think nobody is working on #70, so that should be good starting point if you want to fix a bigger problem. Also this issue is good place to start.

1: currently a notable exception to this is the cursor tooltip, since its completely custom and nvim it self doesn't provide anything for it. This _might_ be replaced in favor of floating windows in future, so gnvim stays closer to nvim.
